### ISSUE TITLE
Confusing error when omitting patch versions in `gleam.toml`

### ISSUE THREAD

**Issue by miutamihai** [gleam-lang/hexpm-rust#33]
Hi, loving learning gleam so far! But trying to create a new `mist` project, I encountered this error when running `gleam build`:
```
error: Dependency resolution failed

An error occurred while determining what dependency packages and
versions should be downloaded.
The error from the version resolver library was:

An unrecoverable error happened while solving dependencies: Failed to parse
range encountered unexpected token: " "
```

Upon inspection it turns out that:
```
# gleam.toml

[dependencies]
# The following is fine
mist = ">= 1.2.0 and < 2.0.0"
# The following isn't
mist = ">= 1.2 and < 2.0"
```

It turns out that if using the version ranges you omit the patch version, you get this cryptic error message (works for any dependency I've tried it on). Diving into the code points to the `range` function in the version parser errorring out:
![image](https://github.com/gleam-lang/hexpm-rust/assets/23569938/d2265303-0e52-45ca-90c7-cbe47af96153)
![image](https://github.com/gleam-lang/hexpm-rust/assets/23569938/93e5094a-14f9-4150-801e-02a66381b9c0)

I'd love to have a crack at fixing this, however I'm not sure what the intended behaviour is here? Do we:
* Allow for version ranges to omit patch versions or
* Add a better error message for this case.

Thoughts?

**Comment by lpil** [comment]
We do not control the syntax for the version constraints as that is set by the hex package manager, so we cannot add this new syntax.

It would be good to have a better error message here though!

**Comment by miutamihai** [comment]
@lpil Opened a PR here: https://github.com/gleam-lang/hexpm-rust/pull/34
